output:
  format: colored-line-number
  sort-results: true

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gci
    - gofumpt
    - interfacer
    - lll
    - maligned
    - scopelint
    - wastedassign
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: generate.go
      linters:
        - gofmt
        - goimports
    - path: _test\.go
      linters:
        - dupl
        - gochecknoglobals
        - goerr113
        - funlen
        - nlreturn
        - unparam
        - wsl

linters-settings:
  maligned:
    suggest-new: true
