name: Go

on: [ push ]

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: '1.20.x'
          check-latest: true
      - name: Tests
        run: | 
          go version
          make tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          cache: false
          go-version: '1.20.x'
          check-latest: true
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Lints
        run: |
          go version
          golangci-lint --version
          make lints
